
const productList = [
    { 
        category: "Top",
        image: "/productImg/topImg.png", 
        name : "후드1후드1후드1후드1후드1후드1후드1",
        price: "3,000",
        descript : "상품 상세 설명 후드 11111상품 상세 설명 후드 11111상품 상세 설명 후드 11111상품 상세 설명 후드 11111상품 상세 설명 후드 11111",
    },
    { 
        category: "Top",
        image: "/productImg/topImg.png", 
        name : "후드2",
        price: "3,000",
        descript : "상품 상세 설명 후드 11111",
    },
    { 
        category: "Top",
        image: "/productImg/topImg.png", 
        name : "후드3",
        price: "3,000",
        descript : "상품 상세 설명 후드 11111",
    },
    { 
        category: "Top",
        image: "/productImg/topImg.png", 
        name : "후드4",
        price: "3,000",
        descript : "상품 상세 설명 후드 11111",
    },
    { 
        category: "Top",
        image: "/productImg/topImg.png", 
        name : "후드5",
        price: "3,000",
        descript : "상품 상세 설명",
    },
    { 
        category: "Top",
        image: "/productImg/topImg.png", 
        name : "후드6",
        price: "3,000",
        descript : "상품 상세 설명",
    },
    { 
        category: "Bottom",
        image: "/productImg/bottomImg.png", 
        name : "바지2",
        price: "3,000",
        descript : "상품 상세 설명",
    },
    { 
        category: "Bottom",
        image: "/productImg/bottomImg.png", 
        name : "바지3",
        price: "3,000",
        descript : "상품 상세 설명",
    },
    { 
        category: "Bottom",
        image: "/productImg/bottomImg.png", 
        name : "바지4",
        price: "3,000",
        descript : "상품 상세 설명",
    },
    { 
        category: "Bottom",
        image: "/productImg/bottomImg.png", 
        name : "바지5",
        price: "3,000",
        descript : "상품 상세 설명",
    },
    { 
        category: "Bottom",
        image: "/productImg/bottomImg.png", 
        name : "바지6",
        price: "3,000",
        descript : "상품 상세 설명",
    },
    { 
        category: "Bottom",
        image: "/productImg/bottomImg.png", 
        name : "바지7",
        price: "3,000",
        descript : "상품 상세 설명",
    },
    { 
        category: "Outer",
        image: "/productImg/OuterImg.png", 
        name : "외투1",
        price: "3,000",
        descript : "상품 상세 설명",
    },
    { 
        category: "Outer",
        image: "/productImg/OuterImg.png", 
        name : "외투2",
        price: "3,000",
        descript : "상품 상세 설명",
    },
    { 
        category: "Outer",
        image: "/productImg/OuterImg.png", 
        name : "외투3",
        price: "3,000",
        descript : "상품 상세 설명",
    },
    { 
        category: "Outer",
        image: "/productImg/OuterImg.png", 
        name : "외투4",
        price: "3,000",
        descript : "상품 상세 설명",
    },
    { 
        category: "Outer",
        image: "/productImg/OuterImg.png", 
        name : "외투5",
        price: "3,000",
        descript : "상품 상세 설명",
    },
    { 
        category: "Outer",
        image: "/productImg/OuterImg.png", 
        name : "외투6",
        price: "3,000",
        descript : "상품 상세 설명",
    },
    { 
        category: "Skirt/Ops",
        image: "/productImg/skirtImg.png", 
        name : "치마1",
        price: "3,000",
        descript : "상품 상세 설명",
    },
    { 
        category: "Skirt/Ops",
        image: "/productImg/skirtImg.png", 
        name : "치마2",
        price: "3,000",
        descript : "상품 상세 설명",
    },
    { 
        category: "Skirt/Ops",
        image: "/productImg/skirtImg.png", 
        name : "치마3",
        price: "3,000",
        descript : "상품 상세 설명",
    },
    { 
        category: "Skirt/Ops",
        image: "/productImg/skirtImg.png", 
        name : "치마4",
        price: "3,000",
        descript : "상품 상세 설명",
    },
    { 
        category: "Skirt/Ops",
        image: "/productImg/skirtImg.png", 
        name : "치마5",
        price: "3,000",
        descript : "상품 상세 설명",
    },
    { 
        category: "Skirt/Ops",
        image: "/productImg/skirtImg.png", 
        name : "치마6",
        price: "3,000",
        descript : "상품 상세 설명",
    },
    { 
        category: "Skirt/Ops",
        image: "/productImg/skirtImg.png", 
        name : "치마7",
        price: "3,000",
        descript : "상품 상세 설명",
    },
    { 
        category: "Etc",
        image: "/productImg/etcImg.png", 
        name : "목걸이1",
        price: "3,000",
        descript : "상품 상세 설명",
    },
    { 
        category: "Etc",
        image: "/productImg/etcImg.png", 
        name : "목걸이2",
        price: "3,000",
        descript : "상품 상세 설명",
    },
    { 
        category: "Etc",
        image: "/productImg/etcImg.png", 
        name : "목걸이3",
        price: "3,000",
        descript : "상품 상세 설명",
    },
    { 
        category: "Etc",
        image: "/productImg/etcImg.png", 
        name : "목걸이4",
        price: "3,000",
        descript : "상품 상세 설명",
    },
    { 
        category: "Etc",
        image: "/productImg/etcImg.png", 
        name : "목걸이5",
        price: "3,000",
        descript : "상품 상세 설명",
    },
    { 
        category: "Etc",
        image: "/productImg/etcImg.png", 
        name : "목걸이6",
        price: "3,000",
        descript : "상품 상세 설명",
    },
    { 
        category: "Etc",
        image: "/productImg/etcImg.png", 
        name : "목걸이7",
        price: "3,000",
        descript : "상품 상세 설명",
    },
    { 
        category: "Etc",
        image: "/productImg/etcImg.png", 
        name : "목걸이8",
        price: "3,000",
        descript : "상품 상세 설명",
    },
    { 
        category: "Etc",
        image: "/productImg/etcImg.png", 
        name : "목걸이9",
        price: "3,000",
        descript : "상품 상세 설명",
    },
];
export default productList;